version: "3.6"

services:
  asim_mysql:
    image: "mysql:${mysql_version}"
    environment:
      MYSQL_ROOT_PASSWORD: "${mysql_root_passwd}"
      MYSQL_DATABASE: "${mysql_database}"
      MYSQL_USER: "${mysql_user}"
      MYSQL_PASSWORD: "${mysql_user_passwd}"
    volumes:
      - ./asimsql:/var/lib/mysql
    networks:
      - mynet

  asim_com:
    image: "wordpress:${wp_version}"
    environment:
      WORDPRESS_DB_HOST: "${asim_wp_db_host}"
      WORDPRESS_DB_USER: "${wp_db_user}"
      WORDPRESS_DB_PASSWORD: "${wp_db_passwd}"
      WORDPRESS_DB_NAME: "${wp_db_name}"
      WORDPRESS_TABLE_PREFIX: wp_
    volumes:
      - ./asim:/var/www/html
      - ./php/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
    depends_on:
      - asim_mysql
    networks:
      - mynet
        #ports:
            #- 8090:80

  majid_mysql:
    image: "mysql:${mysql_version}"
    environment:
      MYSQL_ROOT_PASSWORD: "${mysql_root_passwd}"
      MYSQL_DATABASE: "${mysql_database}"
      MYSQL_USER: "${mysql_user}"
      MYSQL_PASSWORD: "${mysql_user_passwd}"
    volumes:
      - ./majidsql:/var/lib/mysql
    networks:
      - mynet


  majid_com:
    image: "wordpress:${wp_version}"
    environment:
      WORDPRESS_DB_HOST: "${majid_wp_db_host}"
      WORDPRESS_DB_USER: "${wp_db_user}"
      WORDPRESS_DB_PASSWORD: "${wp_db_passwd}"
      WORDPRESS_DB_NAME: "${wp_db_name}"
      WORDPRESS_TABLE_PREFIX: wp_
    volumes:
      - ./majid:/var/www/html
      - ./php/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
    depends_on:
      - majid_mysql
    networks:
      - mynet
        #ports:
        #- 8090:80

volumes:
  asim: {}
  majid: {}
  mysql: {}
networks:
  mynet:
